apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test-tencentcfs
  namespace: kube-system
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: cfsauto
  resources:
    requests:
      storage: 10Gi
